# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-24 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='has_taken_exam',
        ),
        migrations.AddField(
            model_name='candidate',
            name='has_not_taken_exam',
            field=models.BooleanField(default=True),
        ),
    ]
