# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20170426_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='current_message',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='previous_message',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
