# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-28 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20170426_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.ExamSession')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='first',
            field=models.BooleanField(default=False),
        ),
    ]
